version: '3'

services:
  
  fullnode:
    container_name: fullnode
    image: core
    ports:
      - "8080:8080"
      - "8090:8090"
      - "37672:37672"
      - "2001:2001"
    environment:
      - 'BITSHARESD_RPC_ENDPOINT=0.0.0.0:8090'
    volumes:
      - "bitshares-fullnode:/var/lib/bitshares"
      - "./bitshares-core/docker:/etc/bitshares"

  delayed_node:
    container_name: delayed_node
    image: core
    ports:
      - "8081:8080"
      - "8091:8090"
      - "37673:37672"
      - "2002:2001"
    environment:
      - 'BITSHARESD_RPC_ENDPOINT=0.0.0.0:8090'
      - 'BITSHARESD_PLUGINS=delayed_node witness'
      - 'BITSHARESD_TRUSTED_NODE=ws://fullnode:8090'
    volumes:
      - "bitshares-delayed_node:/var/lib/bitshares"
      - "./bitshares-core/docker:/etc/bitshares"


volumes: 
  bitshares-fullnode: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /media/storage/crypto/bitshares/fullnode
  bitshares-delayed_node: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /media/storage/crypto/bitshares/delayed_node
